---
- name: Ansible ec2 launch
  hosts: localhost
  connection: local
  gather_facts: False
  tags: provisioning

  vars:
    instance_type: t2.small
    instance_name: test-ec2-instance
    image: ami-00f07845aed8c0ee7
    wait: yes
    group: webserver
    region: eu-central-1
    lb: alb
    security_group: security-group-test
    ec2_access_key: ""
    ec2_secret_key: ""

  tasks:
  - name: configuring security group for the instance
    ec2_group:
        name: "{{ security_group }}"
        description: security-group-test
        ec2_access_key: "{{ ec2_access_key }}"
        ec2_secret_key: "{{ ec2_secret_key }}"
        region: "{{ region }}"
        rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 8080
              to_port: 8080
              cidr_ip: 0.0.0.0/0
        rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0

  - name: creating ec2 instance
    ec2_instance:
        security_group: "{{ security_group }}"
        name: "{{ instance_name }}"
        ec2_access_key: "{{ ec2_access_key }}"
        ec2_secret_key: "{{ ec2_secret_key }}"
        instance_type: "{{ instance_type}}"
        image_id: "{{ image }}"
        region: "{{ region }}"
        wait_timeout: 3

  - name: creating Load Balancer of ec2
    ec2_elb_lb:
        security_group: "{{ security_group }}"
        name_lb: "{{ lb }}"
        state: present
        ec2_access_key: "{{ ec2_access_key }}"
        ec2_secret_key: "{{ ec2_secret_key }}"
        region: "{{ region }}"
        listerners:
          - protocol: HTTP
            load_balancer_port: 80

  - name: adding instance ec2 to LB
    ec2_lb:
        security_group: "{{ security_group }}"
        target_id: "{{ instance_name }}"
        state: present
        ec2_access_key: "{{ ec2_access_key }}"
        ec2_secret_key: "{{ ec2_secret_key }}"
