---
- name: Ansible ec2 launch
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - /etc/ansible/vars/vars.yaml

  vars:
    instance_type: t2.small
    instance_name: test-ec2-instance
    image: ami-00f07845aed8c0ee7
    wait: yes
    group: webserver
    region: eu-central-1
    security_group: security-group-test

  tasks:
    - name: terminating ec2 instance
      ec2_instance:
        state: absent
        name: "{{ instance_name }}"
        ec2_access_key: "{{ ec2_access_key }}"
        ec2_secret_key: "{{ ec2_secret_key }}"
        region: "{{ region }}"
      delegate_to: localhost

    - name: cleanup security group for the instance
      ec2_group:
        name: "{{ security_group }}"
        description: security-group-test
        ec2_access_key: "{{ ec2_access_key }}"
        ec2_secret_key: "{{ ec2_secret_key }}"
        region: "{{ region }}"
        state: absent
      delegate_to: localhost
